name: DOAS_project
channels:
  - pytorch
  - nvidia   # Optional: good for Linux users, ignored by Mac
  - defaults
dependencies:
  - python=3.11
  - pip
  # The essential "top-level" libraries
  - pytorch=2.5.1
  - torchvision=0.20.1
  # (Note: torchaudio was missing in your file. Add it if you need audio processing)
  - torchaudio=2.5.1
  - pip:
    - ultralytics==8.4.11